2024-Wed-11 15:43:33 [   DEBUG] [urllib3.connectionpool] Starting new HTTPS connection (1): simple-books-api.glitch.me:443 (connectionpool.py:1051)
2024-Wed-11 15:43:34 [   DEBUG] [urllib3.connectionpool] https://simple-books-api.glitch.me:443 "POST /api-clients HTTP/11" 201 82 (connectionpool.py:546)
2024-Wed-11 15:43:34 [   DEBUG] [urllib3.connectionpool] Starting new HTTPS connection (1): simple-books-api.glitch.me:443 (connectionpool.py:1051)
2024-Wed-11 15:43:36 [   DEBUG] [urllib3.connectionpool] https://simple-books-api.glitch.me:443 "POST /orders HTTP/11" 201 50 (connectionpool.py:546)
2024-Wed-11 15:43:36 [   DEBUG] [urllib3.connectionpool] Starting new HTTPS connection (1): simple-books-api.glitch.me:443 (connectionpool.py:1051)
2024-Wed-11 15:43:37 [   DEBUG] [urllib3.connectionpool] https://simple-books-api.glitch.me:443 "POST /orders HTTP/11" 401 41 (connectionpool.py:546)
2024-Wed-11 15:43:37 [    INFO] [testsimpleBookApi.test_Place_new_Order_ofBook] placing order without token (test_Place_new_Order_ofBook.py:45)
2024-Wed-11 15:43:37 [   DEBUG] [urllib3.connectionpool] Starting new HTTPS connection (1): simple-books-api.glitch.me:443 (connectionpool.py:1051)
2024-Wed-11 15:43:39 [   DEBUG] [urllib3.connectionpool] https://simple-books-api.glitch.me:443 "POST /orders HTTP/11" 400 38 (connectionpool.py:546)
2024-Wed-11 15:43:39 [    INFO] [testsimpleBookApi.test_Place_new_Order_ofBook] placeing order with invalid user with token (test_Place_new_Order_ofBook.py:59)
2024-Wed-11 15:43:39 [   DEBUG] [urllib3.connectionpool] Starting new HTTPS connection (1): simple-books-api.glitch.me:443 (connectionpool.py:1051)
2024-Wed-11 15:43:40 [   DEBUG] [urllib3.connectionpool] https://simple-books-api.glitch.me:443 "POST /orders HTTP/11" 201 50 (connectionpool.py:546)
2024-Wed-11 15:43:40 [   DEBUG] [urllib3.connectionpool] Starting new HTTPS connection (1): simple-books-api.glitch.me:443 (connectionpool.py:1051)
2024-Wed-11 15:43:41 [   DEBUG] [urllib3.connectionpool] https://simple-books-api.glitch.me:443 "GET /orders/XEP_1tI9XtxPGmp9ksCfq HTTP/11" 200 190 (connectionpool.py:546)
2024-Wed-11 15:43:41 [   DEBUG] [urllib3.connectionpool] Starting new HTTPS connection (1): simple-books-api.glitch.me:443 (connectionpool.py:1051)
2024-Wed-11 15:43:43 [   DEBUG] [urllib3.connectionpool] https://simple-books-api.glitch.me:443 "POST /logout HTTP/11" 404 146 (connectionpool.py:546)
